services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: moeroot
      MYSQL_DATABASE: photodb
      MYSQL_USER: root
      MYSQL_PASSWORD: moeroot
    networks:
      - backend
    container_name: moe-mysql-app
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql                # Persistent storage for MySQL data
      - ./Database Files/photodb.sql:/docker-entrypoint-initdb.d/photodb.sql # SQL file to set up tables and data
      - ./scripts/init-check.sh:/docker-entrypoint-initdb.d/init-check.sh # Script to check and load data
      - ./scripts/custom-entrypoint.sh:/custom-entrypoint.sh
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  nodejs:
    build:
      context: .
    image: nodejs-app
    environment:
      DB_HOST: moe-mysql-app
      DB_USER: root
      DB_PASSWORD: moeroot
      DB_NAME: photodb
    depends_on:
      - mysql
    networks:
      - backend
      - frontend
    container_name: moe-nodejs-app
    ports:
      - "8005:8005"
    volumes:
      - ./www:/usr/src/app/www                # Static files for the app
      - ./views:/usr/src/app/views            # EJS views
      - ./public:/usr/src/app/public          # Public assets like CSS, images, and uploads

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    depends_on:
      - mysql
    environment:
      PMA_HOST: moe-mysql-app
      MYSQL_ROOT_PASSWORD: moeroot
    networks:
      - backend
    container_name: moe-phpmyadmin-app
    ports:
      - "8080:80"

networks:
  frontend:
  backend:

volumes:
  mysql-data:
