version: '3.8'

services:
  app:
    image: ${{ secrets.DOCKER_USERNAME }}/photography-app:latest
    ports:
      - "8005:8005"  # Expose port 8005 for Node.js app
    environment:
      - DB_HOST=photography-app_db_1  # Use the service name from docker-compose
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=my-secret-pw
      - DB_NAME=photodb
    depends_on:
      - db
    networks:
      - backend
      - frontend

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: photodb
    ports:
      - "3307:3306"  # Expose MySQL port to the host
    networks:
      - backend
    container_name: photography-app_db_1  # Ensure the container name is used as DB_HOST

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    depends_on:
      - db
    environment:
      PMA_HOST: photography-app_db_1  # Link phpMyAdmin with the MySQL container
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "8011:80"
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  mysql-data:
